services:
  - type: web
    name: wrapp-delights
    env: python
    plan: free
    disk:
      name: wrapp-delights-media
      mountPath: /var/data
      sizeGB: 1
    buildCommand: bash build.sh
    startCommand: python delights_backend/core/manage.py migrate && gunicorn delights_backend.core.core.wsgi:application --chdir delights_backend/core
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DJANGO_SETTINGS_MODULE
        value: delights_backend.core.core.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: wrapp-delights-db
          property: connectionString
      - key: MEDIA_ROOT
        value: /var/data/media

databases:
  - name: wrapp-delights-db
    plan: free
